[admin login data]
url= https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
Username = Admin
Password = admin123
invalid_Username = inValidAdmin

#this config.ini file is a configuration file used to store configuration settings/data for the application
#this file consists of data stored in the format of sections, keys and values